export const learnTopics = [
  { slug: 'digital-pollution', title: 'What is Digital Pollution?', icon: 'Cloud', content: 'Digital pollution refers to the environmental impact generated by digital technologies, from manufacturing devices to running data centers. We cover server energy use, e-waste, and more.' },
  { slug: 'repair-reuse', title: 'Why Repair Instead of Throw Away?', icon: 'Wrench', content: 'Embracing the right to repair extends device lifespans, drastically reducing the demand for new resource-intensive manufacturing.' },
  { slug: 'open-source-benefits', title: 'Benefits of Open Source', icon: 'Code', content: 'Open Source software is key to a responsible digital world. It offers transparency, security, and avoids vendor lock-in.' },
  { slug: 'screen-time-balance', title: 'Screen Time Balance', icon: 'Clock', content: 'Achieving a healthy screen time balance is crucial for mental well-being and digital inclusivity.' },
  { slug: 'cybersecurity-basics', title: 'Cybersecurity Basics', icon: 'Shield', content: 'Essential tips for protecting your personal data and digital identity. Topics include strong passwords and two-factor authentication.' },
  { slug: 'eco-design', title: 'Eco-design Principles', icon: 'Leaf', content: 'Learn how software and hardware can be designed to minimize resource consumption, energy use, and material waste.' },
];

// Mock data for FunZone badges (kept here for FunZone.jsx)
export const mockBadges = [
  { name: "Screen Time Hero", description: "Successfully logged a balanced screen time week.", icon: 'Clock', color: 'text-yellow-600' },
  { name: "Digital Cleaner", description: "Completed the three-step cleanup guide.", icon: 'Trash2', color: 'text-green-600' },
  { name: "Open Source Explorer", description: "Installed and used an open-source alternative.", icon: 'Code', color: 'text-nird-violet' },
  { name: "Eco-Designer Beginner", description: "Read the Eco-design principles page.", icon: 'Leaf', color: 'text-blue-600' },
];